### ISSUE TITLE
Me aparece en blanco la página ya creada!

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/Blog_Personal#1]
Eché a correr mi página y agregué una hoja de estilos directamente al HTML, pero no me quería funcionar, si es que mi compañero organizador me puede ayudar!

Saludos!

**Comment by Autinfit** [comment]
Estimado:

Si no agregas al menos un contenido en formato HTML, entonces podría aparecer todo en blanco la página, ya que a priori debes de agregar al menos un contenido mucho más simple del HTML, como por ejemplo, un encabezado, barras de navegación, formularios de contacto, boletines informativos y pie de página, y después de eso, incluyes un decorado mediante una hoja de estilos en formato CSS!

Saludos y espero te sirva de ayuda!

**Comment by MARSFOREVER472** [comment]
Gracias estimado!

Ahora sí quedé todo claro con esta información!

Saludos!
